language: node_js
node_js:
  - "12"
cache: 
  yarn: true
  directories: 
    - node_modules 
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build 
  repo: binarycasper/encrypter-decrypter
  target-branch: master
  keep-history: true
  on:
    branch: master 
